[versions]
coroutines = "1.6.0-native-mt"
kotlin = "1.6.10"
ktor = "2.0.0-beta-1"
okhttp = "3.14.9"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlinx-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.3.1" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }